import type { ReactNode } from 'react';

import { Providers } from '@/components/providers/providers';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { fonts } from './fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(fonts)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
